<a href="https://colab.research.google.com/github/Shurara-san/NLP/blob/Lesson11/Lesson11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers
import transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
from transformers import TFAutoModelForTokenClassification, AutoTokenizer
import tensorflow as tf

In [3]:
import numpy as np
import tensorflow as tf
from transformers import TFAutoModel, AutoTokenizer

In [4]:
bert = TFAutoModel.from_pretrained("Geotrend/bert-base-ru-cased")
tokenizer = AutoTokenizer.from_pretrained("Geotrend/bert-base-ru-cased")

Some layers from the model checkpoint at Geotrend/bert-base-ru-cased were not used when initializing TFBertModel: ['mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at Geotrend/bert-base-ru-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [5]:
!wget https://github.com/ods-ai-ml4sg/proj_news_viz/releases/download/data/gazeta.csv.gz

--2022-07-19 12:38:01--  https://github.com/ods-ai-ml4sg/proj_news_viz/releases/download/data/gazeta.csv.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/150244024/32420400-b8b5-11ea-8264-2539b75fc310?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220719%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220719T123801Z&X-Amz-Expires=300&X-Amz-Signature=59e27389f2437078a99a81662d54cd6b41c675b66c47c93980241be96a4be1a2&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=150244024&response-content-disposition=attachment%3B%20filename%3Dgazeta.csv.gz&response-content-type=application%2Foctet-stream [following]
--2022-07-19 12:38:01--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/150244024/32420400-b8b5-11ea-8264-2539b75fc310?X-Am

In [6]:
path_to_file = "/content/gazeta.csv.gz"

In [7]:
!ls /content/

gazeta.csv.gz  gazeta.csv.gz.1	sample_data


In [8]:
import re

In [9]:
def preprocess_sentence(w):
  w = w.lower().strip()

  # creating a space between a word and the punctuation following it
  # eg: "he is a boy." => "he is a boy ."
  # Reference:- https://stackoverflow.com/questions/3645931/python-padding-punctuation-with-white-spaces-keeping-punctuation
  w = re.sub(r"([?.!,])", r" \1 ", w)
  w = re.sub(r'[" "]+', " ", w)

  # replacing everything with space except (a-z, A-Z, ".", "?", "!", ",")
  w = re.sub(r"[^a-zA-Zа-яА-Я?.!,']+", " ", w)

  w = w.strip()

  # adding a start and an end token to the sentence
  # so that the model know when to start and stop predicting.
  w = '<start> ' + w + ' <end>'
  return w

In [10]:
preprocess_sentence("I can't go.")

"<start> i can't go . <end>"

In [11]:
!pip install corus

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [12]:
from corus import load_ods_gazeta
path = 'gazeta.csv.gz'
records = load_ods_gazeta(path)
# next(records).text

In [13]:
import torch

In [161]:
toks_array = []
texts_array = []
berts_array = []
next_record = next(records).text
counter = 0
while counter < 50000:
  preproc = preprocess_sentence(next_record)
  tok_record = tokenizer([preproc], max_length=20, truncation=True, padding='max_length', return_token_type_ids=False, return_tensors='tf')
  # bert_record = bert(**tok_record)
  text_record = next_record
  toks_array.append(tok_record)
  texts_array.append(text_record)
  # berts_array.append(bert_record)
  next_record = next(records).text
  counter += 1

In [79]:
tok = tokenizer(["Кто кому сколько заплатил"], max_length=20, truncation=True, padding='max_length', return_token_type_ids=False, return_tensors='tf')

In [80]:
tok['input_ids']

<tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[   11, 13680,  8672,  1110,   182, 13304,   320,   770,  7760,
          499,    12,     0,     0,     0,     0,     0,     0,     0,
            0,     0]], dtype=int32)>

In [81]:
sum(sum(np.array(tf.math.equal(toks_array[3]['input_ids'], tok['input_ids']))))

1

In [82]:
tf.math.equal(toks_array[3]['input_ids'], tok['input_ids'])

<tf.Tensor: shape=(1, 20), dtype=bool, numpy=
array([[ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False]])>

In [125]:
#def similarities (x, y):
a = np.sort(np.array(toks_array[3]['input_ids']))
b = np.sort(np.array(tok['input_ids']))
sum(sum(np.isin(a,b)))

2

In [149]:
def n_most_relevant_news(request, tok_news, rel_news_number):
  tok_request = tokenizer([request], max_length=20, truncation=True, padding='max_length', return_token_type_ids=False, return_tensors='tf')
  b = np.sort(np.array(tok_request['input_ids']))
  sum_value = 0
  recs = []
  for i in range(len(tok_news)):
    a = np.sort(np.array(tok_news[i]['input_ids']))
    current_value = sum(sum(np.isin(a,b)))
    if sum_value < current_value:
      sum_value = current_value
      recs.append(texts_array[i])
  if len(recs) > rel_news_number: 
    return recs[len(recs)-rel_news_number:]
  elif len(recs) != 0:
    print("Найдено лишь", len(recs), "новости(ь/ей)")
    return recs
  else: return ("Не найдено ни одной релевантной новости")

In [152]:
n_most_relevant_news('Кто кому сколько заплатил', toks_array, 5)

['Француз Жо-Вилфрид Цонга переиграл в полуфинале турнира в Торонто болгарина Григора Димитрова со счетом 2:0 (6:4, 6:3).nТоронто. Rogers Cup. Мужчины.Полуфинал.nЦонга (Франция) — Димитров (Болгария)n— 6:4, 6:3nВо втором полуфинальном матче Роджер Федерерnсыграетnс Фелисьяно Лопесом. Встреча состоится 10 августа в 04.00 мск.nДругие новости, материалы и статистику можно посмотреть наnстраницеnтенниса.',
 'Новичок «Йокерит» готов заплатить Теему Селянне S10 млн (€7,5 млн) за сезон в КХЛ, сообщаетnIlta Sanomatn.nСам Селянне ужеnзаявлялnо желании поиграть за «Йокерит».nРанее 44-летний финнnобъявилnо завершении карьеры.nОзнакомиться с другими новостями, материалами и статистикой вы можете наnстраницеnКонтинентальной хоккейной лиги.',
 'Испанская «Барселона» заплатила за защитника «Арсенала» и сборной Бельгии Томаса Вермалена € 10 млн, сообщаетnофициальный сайт каталонцевn.nСумма может вырасти до € 18,8 млн: бонус в € 5 млн зависит от выступления Вермалена, а € 3,8 млн лондонскому клубу дост

In [153]:
n_most_relevant_news('Кто кому сколько заплатил', toks_array, 3)

['Испанская «Барселона» заплатила за защитника «Арсенала» и сборной Бельгии Томаса Вермалена € 10 млн, сообщаетnофициальный сайт каталонцевn.nСумма может вырасти до € 18,8 млн: бонус в € 5 млн зависит от выступления Вермалена, а € 3,8 млн лондонскому клубу достанется в случае победы «Барселоны» в Лиге чемпионов.nБельгиецnподписалnс сине-гранатовыми пятилетний контракт. В «Барселоне» Вермален будет выступать под 23-м номером.nОзнакомиться с другими новостями, материалами и статистикой вы можете наnстраницеnиспанского футбола.',
 'Московский «Спартак» заплатил Российскому футбольному союзу (РФС) 5 млн руб. в качестве налога за швейцарского тренера Мурата Якина, сообщаетnИТАР-ТАССn.nС 1 июня 2013 года клубы Премьер-лиги, заявляющие иностранца на пост главного тренера, должны выплачивать РФС 5 млн руб.nРанееnстало известноn, что подобный налог заплатил «Амкар» за сербского специалиста Славолюба Муслина.nОзнакомиться с другими материалами, новостями и статистикой вы можете наnстраницеnчемпи

In [154]:
n_most_relevant_news('Кто кому сколько заплатил', toks_array, 10)

Найдено лишь 7 новости(ь/ей)


['Олимпийский чемпион 1988 года Шарунас Марчюленис введен в Зал славы НБА, сообщаетnESPNn.nС 1989 года литовский баскетболист в НБА выступал за «Голден Стэйт», «Сиэтл», «Сакраменто» и «Денвер». Он также играл за сборную Литвы, вместе с которой дважды (в 1992 и 1996 годах) выигрывал бронзовые медали Олимпийских игр.nТакже новыми членами Зала славы баскетбола стали бывший комиссионер лиги Дэвид Стерн, экс-тренер «Индианы» Боб Ленард, бывший игрок «Никс» Нэт Клифтон, Гай Роджерс, прославленные игроки Алонзо Моурнинг и Митч Ричмонд, чемпионская команда университета Иммакулата начала 70-х, тренеры Нолан Ричардсон и Гэри Уильямс.nОзнакомиться с другими новостями, материалами и статистикой вы можете наnстраницеnНациональной баскетбольной ассоциации.',
 'Российский хоккеист Федор Федоров может завершить карьеру.n«Федор поедет в Швейцарию на командный сбор, и там тренеры будут принимать решение», — заявил Сергей Федоров в интервьюnофициальному сайтуnЦСКА. В той же публикации на вопрос: «Правда 

In [156]:
n_most_relevant_news('Кто кому сколько заплатил?', toks_array, 5)

['Француз Жо-Вилфрид Цонга переиграл в полуфинале турнира в Торонто болгарина Григора Димитрова со счетом 2:0 (6:4, 6:3).nТоронто. Rogers Cup. Мужчины.Полуфинал.nЦонга (Франция) — Димитров (Болгария)n— 6:4, 6:3nВо втором полуфинальном матче Роджер Федерерnсыграетnс Фелисьяно Лопесом. Встреча состоится 10 августа в 04.00 мск.nДругие новости, материалы и статистику можно посмотреть наnстраницеnтенниса.',
 'Новичок «Йокерит» готов заплатить Теему Селянне S10 млн (€7,5 млн) за сезон в КХЛ, сообщаетnIlta Sanomatn.nСам Селянне ужеnзаявлялnо желании поиграть за «Йокерит».nРанее 44-летний финнnобъявилnо завершении карьеры.nОзнакомиться с другими новостями, материалами и статистикой вы можете наnстраницеnКонтинентальной хоккейной лиги.',
 'Испанская «Барселона» заплатила за защитника «Арсенала» и сборной Бельгии Томаса Вермалена € 10 млн, сообщаетnофициальный сайт каталонцевn.nСумма может вырасти до € 18,8 млн: бонус в € 5 млн зависит от выступления Вермалена, а € 3,8 млн лондонскому клубу дост

In [157]:
n_most_relevant_news('Последние новости сферы финансов', toks_array, 5)

Найдено лишь 5 новости(ь/ей)


['Олимпийский чемпион 1988 года Шарунас Марчюленис введен в Зал славы НБА, сообщаетnESPNn.nС 1989 года литовский баскетболист в НБА выступал за «Голден Стэйт», «Сиэтл», «Сакраменто» и «Денвер». Он также играл за сборную Литвы, вместе с которой дважды (в 1992 и 1996 годах) выигрывал бронзовые медали Олимпийских игр.nТакже новыми членами Зала славы баскетбола стали бывший комиссионер лиги Дэвид Стерн, экс-тренер «Индианы» Боб Ленард, бывший игрок «Никс» Нэт Клифтон, Гай Роджерс, прославленные игроки Алонзо Моурнинг и Митч Ричмонд, чемпионская команда университета Иммакулата начала 70-х, тренеры Нолан Ричардсон и Гэри Уильямс.nОзнакомиться с другими новостями, материалами и статистикой вы можете наnстраницеnНациональной баскетбольной ассоциации.',
 'Вратарь английского «Фулхэма» Мартен Стекеленбург перейдет в «Монако», сообщает журналист телеканала «Ma Chaîne Sport» Николас Виласnна своей странице в твиттереn.nГолландец перейдет в новый клуб на правах свободного агента. Другие детали сдел

In [158]:
n_most_relevant_news('Важно беречь здоровье', toks_array, 5)

Найдено лишь 3 новости(ь/ей)


['Олимпийский чемпион 1988 года Шарунас Марчюленис введен в Зал славы НБА, сообщаетnESPNn.nС 1989 года литовский баскетболист в НБА выступал за «Голден Стэйт», «Сиэтл», «Сакраменто» и «Денвер». Он также играл за сборную Литвы, вместе с которой дважды (в 1992 и 1996 годах) выигрывал бронзовые медали Олимпийских игр.nТакже новыми членами Зала славы баскетбола стали бывший комиссионер лиги Дэвид Стерн, экс-тренер «Индианы» Боб Ленард, бывший игрок «Никс» Нэт Клифтон, Гай Роджерс, прославленные игроки Алонзо Моурнинг и Митч Ричмонд, чемпионская команда университета Иммакулата начала 70-х, тренеры Нолан Ричардсон и Гэри Уильямс.nОзнакомиться с другими новостями, материалами и статистикой вы можете наnстраницеnНациональной баскетбольной ассоциации.',
 'Полузащитник «Краснодара» Марат Измайлов заявил, что в 2010 году мог стать игроком московского «Локомотива».n«В 2010-м я даже прошел для «Локомотива» медобследование в Риме. Можно сказать, одной ногой вернулся. Но в последний момент все мы реш

In [162]:
n_most_relevant_news('Новости тенниса', toks_array, 5)

Найдено лишь 4 новости(ь/ей)


['Саратовский «Автодор» обыграл украинский «Химик» со счетом 93:80 в домашнем матче восьмого тура группового этапа Лиги чемпионов ФИБА.nСамым результативным игроком встречи стал разыгрывающий «Химика» Джейми Смит, который набрал 22 очка.nЛига чемпионов ФИБА. Группа B. 8-й тур.nn«Автодор» — «Химик» — 93:80 (16:19, 30:20, 18:22, 29:19)n«Автодор»:nМиннерат (21), Хантер (15), Колесников (13), Быков (12), Фрейзер (12), Колюшкин (7), Макиев (6), Каррера (4), Астапкович (3), Баландин, Стоктон.n«Химик»:nСмит (22), Конев (12), Петров (11), Лав (10), Беджарано (8), Прокопенко (8), Антипов (4), Павлов (3), Беликов (2), Ковалёв, Рябчук, Сидоров.',
 'Аргентинский теннисист Хуан-Мартин дель Потро в матче первого раунда турнира в Делрэй-Бич (США) нанес поражение Кевину Андерсону из ЮАР со счетом 6:4, 6:4.nВ каждой из партий аргентинец сделал по одному брейку. На его счету пять эйсов и четыре ошибки на подаче. Андерсон подал навылет девять раз и допустил одну двойную ошибку.nСледующим соперником дель 

In [163]:
n_most_relevant_news('Международные отношения', toks_array, 5)

Найдено лишь 3 новости(ь/ей)


['Саратовский «Автодор» обыграл украинский «Химик» со счетом 93:80 в домашнем матче восьмого тура группового этапа Лиги чемпионов ФИБА.nСамым результативным игроком встречи стал разыгрывающий «Химика» Джейми Смит, который набрал 22 очка.nЛига чемпионов ФИБА. Группа B. 8-й тур.nn«Автодор» — «Химик» — 93:80 (16:19, 30:20, 18:22, 29:19)n«Автодор»:nМиннерат (21), Хантер (15), Колесников (13), Быков (12), Фрейзер (12), Колюшкин (7), Макиев (6), Каррера (4), Астапкович (3), Баландин, Стоктон.n«Химик»:nСмит (22), Конев (12), Петров (11), Лав (10), Беджарано (8), Прокопенко (8), Антипов (4), Павлов (3), Беликов (2), Ковалёв, Рябчук, Сидоров.',
 'Главный тренер сборной России Олег Знарок прокомментировал победу над Финляндией (8:1) в матче Кубка Первого канала.n«Мы сделали правильные выводы после шведов, у нас сегодня многое получалось. Завтрашняя игра важная, готовимся к ней.nЧто касается звена с Радуловым и Ковальчуком, то мы в поиске, потому что у нас еще есть время. Сыграла команда, кого-то